### ISSUE TITLE
unicorn_role setting not used

### ISSUE THREAD

**Issue by mhuggins** [scarfacedeb/mina-unicorn#11]
I'm deploying via user `deployer`, but I want my unicorn process to run under user `rails`.  I tried changing this setting, but I then realized it's not actually being used in the code anywhere.

**Comment by scarfacedeb** [comment]
@mhuggins you're right!
I guess the original author of the gem copied this setting blindly (probably from capistrano-unicorn).

Thank you for bringing it up, I removed it to prevent further confusion.

btw, you can use `user` setting in unicorn config to change its user.
see: http://unicorn.bogomips.org/Unicorn/Configurator.html
