### ISSUE TITLE
Unicorn searching gems in outdated releases

### ISSUE THREAD

**Issue by thiagogsr** [scarfacedeb/mina-unicorn#13]
Hi there

I'm using mina and mina-unicorn to deploy my app, but the unicorn is searching the gems in outdated releases. My current release is 230, but an error is raised because Unicorn did not found the gem in release 204.

My `deploy.rb` is here: https://gist.github.com/thiagogsr/aae6e4f7cbccf0071736

Error:
```
cannot load such file -- /home/user/app/releases/204/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/em_http
```

**Comment by greatghoul** [comment]
```
    to :launch do
      invoke :'unicorn:stop'
      invoke :'unicorn:start'
    end
```

I got the same error, stop then start instead of restart to solve it.

**Comment by scarfacedeb** [comment]
@thiagogsr I'm trying to reproduce it.

Does your `pid` config variable from `config/unicorn.rb` match with `unicorn_pid` mina variable?

**Comment by scarfacedeb** [comment]
Here's sample app that I'm using to test mina-unicorn deploys:
https://github.com/scarfacedeb/mina-unicorn-test
