### ISSUE TITLE
Using mina/unicorn with rails - where does the rails environment get set?

### ISSUE THREAD

**Issue by pypestream-server** [scarfacedeb/mina-unicorn#15]
When using this with rails, where does the rails environment get set?

When using these tasks, I get unicorn with "-E deployment", which is the rack environment. I can't find where the rails environment is set anywhere.

Where does this happen?

**Comment by scarfacedeb** [comment]
@pypestream-server Looking at [Rails#env](https://github.com/rails/rails/blob/d25fe31c40928712b5e08fe0afb567c3bc88eddf/railties/lib/rails.rb#L59) source code, it seems like it's also using `RACK_ENV` (that unicorn is setting).

Have you tried to set `unicorn_env` variable in mina?

**Comment by scarfacedeb** [comment]
@pypestream-server I was wrong, mina-unicorn sets `RAILS_ENV` itself.

It's using `bundle_prefix` mina variable from [mina/rails](https://github.com/mina-deploy/mina/blob/master/lib%2Fmina%2Frails.rb#L25) that adds `RAILS_ENV=#{rails_env} bundle exec` to `unicorn` command.

I was able to change `RAILS_ENV` by adding:
```ruby
set :rails_env, :development
```
to my deploy.rb
