### ISSUE TITLE
"deployment" environment

### ISSUE THREAD

**Issue by alxx** [scarfacedeb/mina-unicorn#20]
How does this environment work? I've noticed it's hardcoded in your library so that Unicorn starts either as "development" or as "deployment".

How do I avoid needing a "deployment" section in all my YAML configuration files, next to "development", "test" and "production"?

**Comment by scarfacedeb** [comment]
RACK_ENV is not the same thing as RAILS_ENV.

See: http://unicorn.bogomips.org/unicorn_1.html#rack-environment and http://www.hezmatt.org/%7Empalmer/blog/2013/10/13/rack_env-its-not-for-you

**Comment by alxx** [comment]
No offense, but that was _incredibly_ unhelpful.

First of all, I knew about the first link. It's probably the single mention on the entire big Internet about the "deployment" environment, and it's no more helpful than your answer.

Second, it does **not** explain for me, or for the tons of other users who have filled stackoverflow and other sites with similar puzzled questions, work out why _mina:unicorn starts unicorn with -E deployment even for Rails apps_.

It doesn't work. It makes apps crash. It's undocumented. And you're refusing to clarify.

So far, my solution is to start unicorn "by hand" giving it -E production, then only use mina-unicorn for its SIGUSR killing service (restarting unicorn with zero downtime), because that maintains the environment I've initially specified.

**Why** does mina-unicorn insist on starting unicorn with -E deployment?

How is "RACK_ENV not the same as RAILS_ENV" helping me in this case? I know they're two different environment variables. I know RACK_ENV is not the way to configure the Rails environment. So why does mina-unicorn do it then, if I use it with a Rails app?

I'm asking you why you're doing something that seems wrong, and your answer is that yes, it's wrong -- and then you close the ticket?

I fully understand that you're doing this project for free etc etc etc, but could you _please_ be a little more helpful? Or a little less unhelpful?

I see how -E deployment is useful for a Rack app. I have one of those too; I use mina to deploy it, and everything works fine. But for a Rails app, I need it to be "production".

What should I do so mina-unicorn will start my unicorn process with -E production instead of -E deployment?

**Comment by scarfacedeb** [comment]
@alxx I didn't mean to sound rude. I prefer to give short answers when possible. 
I'm sorry, if it didn't help with your issue.
Let's try again? 🕊

I've been asked this question many times and using deployment **IS** the correct way to set `RACK_ENV`. (and unicorn `-E` option)
One of the reasons: https://github.com/defunkt/unicorn/blob/master/lib%2Funicorn.rb#L79

Rails 4 uses `RAILS_ENV` to choose its environment, and you need to set it to `production` to get the desired output.

To do that, you'll need to set `bundle_prefix` in a similar way:
```
set :bundle_prefix, -> { %{RAILS_ENV="#{fetch(:rails_env)}" #{fetch(:bundle_bin)} exec} } 
```

As far as I'm aware, that variable should be set by `mina/rails` by default. 
See: https://github.com/mina-deploy/mina/blob/v0.3.8/lib%2Fmina%2Frails.rb#L17

Mina-unicorn uses `bundle_prefix` to run unicorn:
```
set_default :unicorn_cmd,       -> { "#{bundle_prefix} unicorn" }
```

In the end it gives `RAILS_ENV=production bundle exec unicorn ... -E deployment`.

**Comment by alxx** [comment]
Thanks for the clarification!
