### ISSUE TITLE
mina unicorn:start using wrong directory

### ISSUE THREAD

**Issue by cameronbourgeois** [scarfacedeb/mina-unicorn#21]
When running unicorn start, I get the following error:

```
/html/dev-api/shared/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:88:in `block in reload': directory for pid=/html/shared/tmp/pids/unicorn.pid not writable (ArgumentError)
    from /html/dev-api/shared/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:84:in `each'
    from /html/dev-api/shared/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:84:in `reload'
    from /html/dev-api/shared/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:65:in `initialize'
    from /html/dev-api/shared/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:76:in `new'
    from /html/dev-api/shared/bundle/ruby/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:76:in `initialize'
    from /html/dev-api/current/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `new'
    from /html/dev-api/current/vendor/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
    from /html/dev-api/current/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
    from /html/dev-api/current/vendor/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
master failed to start, check stderr log for details
```

Mina is clearly getting the path to my PID file wrong:

`/html/shared/tmp/pids/unicorn.pid`

should be:

`/html/dev-api/shared/tmp/pids/unicorn.pid`

**Comment by cameronbourgeois** [comment]
I just had some time to look into this again and I can see in the restart_unicorn method that the path to run the unicorn script is being built like so: `#{deploy_to}/#{current_path}`. See [this line of code](https://github.com/scarfacedeb/mina-unicorn/blob/ecc4f3307ca70006a8e109a84e0b1259f8063922/lib/mina/unicorn/utility.rb#L85
).

Does anyone know for what reason the `current_path` is being appended to the path at this point?

In my case, a previous mina task must be moving to a different directory and therefore causing  `unicorn:restart` to choose the wrong path. I have fixed my own script by simply moving the current path to the deploy directory before invoking 

```
    to :launch do
      queue %[cd "#{deploy_to}"]
      invoke :'unicorn:restart'
    end
```

**Comment by cameronbourgeois** [comment]
Another update: The above doesn't work, because at this point the current path has not yet been symlinked! Looking into how I can find the release path...

**Comment by cameronbourgeois** [comment]
ANOTHER update 😉 

The above for some reason only worked when I moved the code into a seperate task like so:

```
task :deploy => :environment do
  deploy do
    # all the things!
    to :launch do
      invoke :'restart'
    end
  end
end

task :restart do
  # mina unicorn gem has a bug, must cd to the release path before restarting.
  queue %[echo "-----> Ensuring unicorn will restart from #{deploy_to}/$release_path"]
  queue %[cd "#{deploy_to}/$release_path"]
  invoke :'unicorn:restart'
end
```

Thanks to the guys over on this issue whom I got the idea from: https://github.com/mina-deploy/mina/issues/432

**Comment by scarfacedeb** [comment]
@cameronbourgeois First of all, thank you for the investigation! 👍 

Unfortunately, I can't reproduce the issue with my setup.

I added small debug line into unicorn:start command in https://github.com/scarfacedeb/mina-unicorn/tree/investigate_current_path

Could you install the gem from it and inspect where does `current_path` points to in your case?

In my case, it points to correct new release path:

```
-----> Starting Unicorn...
       lrwxrwxrwx 1 * * 11 Oct 22 21:16 ***/apps/unicorn_test/current -> releases/25
-----> Done. Deployed v25
```
