### ISSUE TITLE
Forward SECRET_KEY_BASE ?

### ISSUE THREAD

**Issue by xqyww123** [scarfacedeb/mina-unicorn#28]
In my config/secrets.yml:
``` yml
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```
And the command:
```
SECRET_KEY_BASE=foofoofoo mina unicorn:start
```
But doesn't works.
It may be a good feature, isn't it?

**Comment by scarfacedeb** [comment]
The command sets env variable for your shell, but `mina unicorn:start` runs commands on the server.

I don't think it's wise to set env variables on the server from your development machine.
