### ISSUE TITLE
Add to readme

### ISSUE THREAD

**Issue by tiredenzo** [scarfacedeb/mina-unicorn#3]
Hello to make this wonderful app work
you need to add 'tmp/sockets', 'tmp/pids' to set :shared_paths

````
set :shared_paths, ['log', 'tmp/sockets', 'tmp/pids']
````

Maybe it could be written in the readme ?

**Comment by tagliala** [comment]
Hi,

this is because this information on the readme is wrong: https://github.com/scarfacedeb/mina-unicorn#usage

> `unicorn_pid` - unicorn pid file, default `shared/tmp/pids/unicorn.pid`

It actually defaults to `current_path`: https://github.com/scarfacedeb/mina-unicorn/blob/master/lib/mina/unicorn/tasks.rb#L11

@scarfacedeb is this gem still maintained?

**Comment by tagliala** [comment]
Refers to #3

**Comment by scarfacedeb** [comment]
@tiredenzo Thank you for your suggestion, I added it to README.

@tagliala Yes, it's still maintained.

The information in README was correct if you set `shared_paths` as described above.
In other words, `tmp` directory in `"#{deploy_to}/#{current_path}/tmp/pids/unicorn.pid"` path should resolve to a symbolic link to `shared/tmp/pids`.

**Comment by tagliala** [comment]
@scarfacedeb thanks!
