### ISSUE TITLE
Supports mina 0.3.1?

### ISSUE THREAD

**Issue by chao-xian** [scarfacedeb/mina-unicorn#5]
Hi

I'm struggling to get this working as I've just upgraded to mina 0.3.1 from 0.3.0. Can I just confirm that mina-unicorn works with mina 0.3.1? Am using unicorn 4.8.3.

I've noticed that for 0.3.0 in `railsapproot/bin` there's a unicorn script, presumably generated at some point. There isn't one for mina 0.3.1 and I can't spot where this would be generated.

Thanks

**Comment by scarfacedeb** [comment]
I'm using `mina (0.3.2)` in production with `unicorn (4.8.3)` and it works fine.
Could you elaborate what kind of error are you getting?
