### ISSUE TITLE
Doesn't respect mina/bundler's bundle_bin setting

### ISSUE THREAD

**Issue by reedlaw** [scarfacedeb/mina-unicorn#7]
The bundle path should be sourced from `bundle_bin` in case it's not in the PATH.

**Comment by scarfacedeb** [comment]
@reedlaw I'm not sure I understand what you mean.

Are you referring to `:unicorn_cmd` setting?
```ruby
set_default :unicorn_cmd,       -> { "#{bundle_prefix} unicorn" }
```

It uses `bundle_prefix` setting from mina, which takes into account `bundle_bin`.
